### ISSUE TITLE
piedock launched apps forget its theme under kde 5 plasma workspace

### ISSUE THREAD

**Issue by pauledd** [markusfisch/PieDock#10]
This drived me crazy! I reinstalled kde-frameworks/plasma 5.3.2 twice befor I found what caused the problem. In an normal KDE5 session, when I start an application like dolphin or firefox via piedock it does not start with the predefined color/icon scheme. I set my theme to "breeze dark" but dolphin starts in white and without icons. I can also start an terminal through piedock and then start dolphin in it and it forgets its dark theme too. But when I launch those applications normaly from the kde-launcher they start correctly themed/colored. I guess piedock somehow disables something like an kde env. variable? 
I recorded a video that should show the problem:
https://www.youtube.com/watch?v=idfL-23f9M0
Is there any solution to this? Can someone reproduce this?

**Comment by markusfisch** [comment]
My first guess is that piedock wasn't started in a fully configured shell environment. How do you start it? Is it started by KDE?

To confirm my assumption you could kill the running piedock process, then start it again from a terminal you opened from the KDE launcher (from which firefox does start with the right color scheme). Does this change anything?

piedock runs programs by replacing a fork of itself with a new process image (see [execl](http://linux.die.net/man/3/execl) [here](https://github.com/markusfisch/PieDock/blob/master/src/Menu.cpp#L428)) what inherits the environment of piedock to the new process.

**Comment by pauledd** [comment]
Thank you very much for pointing the right direction. I usually start piedock from my .xinitrc like:

>...
piedock &
exec startkde

Then I removed piedock from .xinitrc and started it in an kde session. From that point all themes and colors are proper. I still don't know how to autostart things like piedock in kde5 but that's not a matter of piedock. I think you can close this.

**Comment by markusfisch** [comment]
Glad I could help. Thanks for using piedock.
