### ISSUE TITLE
Making exemption from open-windows

### ISSUE THREAD

**Issue by ArchieA** [markusfisch/PieDock#15]
I'm running conky on KDE Plasma 5.19.2 with kernel 5.7.6 and Qt version 5.15.0, and would like to exclude conky from the icons displayed on open-windows.

**Comment by markusfisch** [comment]
Hi, it's quite easy to ignore certain windows from the dock. You just need to know the "window name" of the window, which you can find with `piedockutils` from the `utils` subdirectory:
```
$ utils/piedockutils -l
```

Then, in your `~/.piedockrc`, add an `ignore-window` statement with the window name, e.g.:
```
ignore-window "gnome-panel"
```

Here's the corresponding sample from `res/piedockrc.sample`:
https://github.com/markusfisch/PieDock/blob/master/res/piedockrc.sample#L160

**Comment by ArchieA** [comment]
Perfect! I really appreciate the instruction. And I'd like to take this opportunity to say thank you for piedock. It is one of my favorite utility app and I use it all the time.

**Comment by markusfisch** [comment]
You're welcome 😉 And glad to hear that 😄
