### ISSUE TITLE
conky not hiding from windows list

### ISSUE THREAD

**Issue by jackholborn** [markusfisch/PieDock#9]
I'm running piedock under compiz WM. Everything goes fine but when I run conky it does appear in piedock's windows list although I kind of blacklisted it in the configuration file. I understand piedock uses WM_NAME so I used piedockutils to find out and also xprop. Then I modified my conkyrc and piedockrc so that I get the same name.
- from piedockrc: 
...
alias name  "Conky" conky
ignore-window "conky"
ignore-window "Conky"
...
icon Conky "conky -c /home/jack/.conky/compizconkyrc"
...

- from xprop:
WM_CLASS(STRING) = "Conky", "Conky"
WM_NAME(STRING) = "Conky"
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_BELOW

- from piedockutils:
Window 0x1600002
	Title: "Conky"
	Name: "Conky"
	Class: "Conky"

I get the same result if I disable skip_pager and skip_taskbar from within conkyrc. Also when I created alias for conky in piedockrc the conky icon in the menu doesn't show up anymore. I had to rename it from Conky.png to conky.png so that I don't get a question mark instead. I may be missing something obvious but I don't see what. Have a look at the screenshot:
![desk](https://cloud.githubusercontent.com/assets/10475641/5691606/8ab18288-98d0-11e4-8c62-0d3acecf0f0e.png)

**Comment by jackholborn** [comment]
Thank you,
This is mostly thanks to contributions like yours to making nice desktop tools. About the ignore-windows directive it seems I misunderstood it's function, thank you for making it clear to me. Indeed it does what it's supposed to.
I was talking about that menu which shows every open windows so you can switch to them, maybe I shouldn't call it "windows list"?
it's defined at: "trigger menu open-windows button-down Mod4 1"

**Comment by markusfisch** [comment]
Oh, I see! That's a bug! Ignored windows shouldn't be in the open windows menu of course.

I just posted a fix for this. Latest version is now 1.6.7 which you may install like this:

	$ git clone git://github.com/markusfisch/PieDock.git
	$ cd PieDock
	$ ./configure && make && sudo make install

**Comment by jackholborn** [comment]
Fantastic!
Everything's just fine now. Thank you for being so quick at solving this.

A+
Jack H.
